//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by ADefragUI.rc
//
#define IDR_CNTR_INPLACE                7
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define ID_REPORT_PRINT                 101
#define IDP_FAILED_TO_CREATE            102
#define ID_REPORT_SAVE                  103
#define IDD_HELPVIEW                    104
#define IDB_DEFRAGSMALL                 110
#define IDB_DEFRAGLARGE                 111
#define IDB_MAIN                        112
#define IDB_BUTTONS                     113
#define IDB_FILELARGE                   114
#define IDB_FILESMALL                   115
#define IDB_SCHEDULERSMALL              116
#define IDB_SCHEDULERLARGE              117
#define IDR_POPUP_SCHEDULERVIEW         118
#define IDR_POPUP_EDIT                  119
#define ID_STATUSBAR_PANE1              120
#define ID_STATUSBAR_PANE2              121
#define IDS_STATUS_PANE1                122
#define IDS_STATUS_PANE2                123
#define IDR_POPUP_DFRAGVIEW             124
#define IDR_MAINFRAME                   128
#define IDR_MAINFRAME_256               129
#define IDR_ADefragReportTYPE           130
#define IDR_TRAY_MENU                   131
#define IDC_BASE_LIST                   132
#define ID_INDICATOR_LABEL              133
#define ID_INDICATOR_PROGRESS           134
#define IDS_TASKPANE_WND                135
#define ID_VIEW_OUTPUTWND               149
#define ID_VIEW_TASKPANE                150
#define IDR_PASTE_MENU                  151
#define IDR_WINDOWS_MENU                152
#define IDS_OUTPUT_WND                  157
#define IDI_OUTPUT_WND                  165
#define IDI_OUTPUT_WND_HC               166
#define IDR_RIBBON_DEFRAG_ORDER         167
#define IDR_OUTPUT_POPUP                182
#define IDR_THEME_MENU                  200
#define ID_SET_STYLE                    201
#define ID_VIEW_APPLOOK_WIN_2000        210
#define ID_VIEW_APPLOOK_OFF_XP          211
#define ID_VIEW_APPLOOK_WIN_XP          212
#define ID_VIEW_APPLOOK_OFF_2003        213
#define ID_VIEW_APPLOOK_VS_2005         214
#define ID_VIEW_APPLOOK_OFF_2007_BLUE   215
#define ID_VIEW_APPLOOK_OFF_2007_BLACK  216
#define ID_VIEW_APPLOOK_OFF_2007_SILVER 217
#define ID_VIEW_APPLOOK_OFF_2007_AQUA   218
#define IDS_RIBBON_MAIN                 260
#define IDS_RIBBON_ABOUT                272
#define IDS_RIBBON_EXIT                 273
#define IDS_RIBBON_DEFRAG               274
#define IDS_RIBBON_DEFRAG_PANEL         275
#define IDS_RIBBON_DEFRAG_ANALYZE       276
#define IDS_RIBBON_FREE_SPACE           277
#define IDS_RIBBON_DEFRAG_SIMPLE        278
#define IDS_RIBBON_PAUSE                279
#define IDS_RIBBON_STOP                 280
#define IDS_RIBBON_OUTPUT_WINDOW        281
#define IDS_RIBBON_SCHEDULER            282
#define IDS_RIBBON_SCHEDULER_NEW_PANEL  283
#define IDS_RIBBON_PROGRESS_PANEL       284
#define IDS_RIBBON_PROGRESS_CURRENT_LABEL 285
#define IDS_RIBBON_SCHEDULE_NEW_ONETIME 286
#define IDS_RIBBON_SCHEDULE_NEW_DAILY   287
#define IDS_RIBBON_SCHEDULE_NEW_WEEKLY  288
#define IDS_RIBBON_SCHEDULE_NEW_SCREENSAVER 289
#define IDS_RIBBON_SCHEDULER_RUN_PANEL  290
#define IDS_RIBBON_SCHEDULE_RUN         291
#define IDS_RIBBON_VIEW_STYLE           292
#define IDS_RIBBON_SCHEDULER_EDIT_PANEL 293
#define IDS_RIBBON_SCHEDULE_ENABLE      294
#define IDS_RIBBON_SCHEDULE_EDIT        295
#define IDS_RIBBON_SCHEDULE_DELETE      296
#define IDS_RIBBON_DEFRAG_COMPUTER      297
#define IDS_RIBBON_DEFRAG_ORDER         298
#define IDS_RIBBON_WINDOW               300
#define IDS_RIBBON_WINDOWS              301
#define IDS_RIBBON_STYLE                302
#define IDS_RIBBON_STYLE_TIP            303
#define IDS_RIBBON_STYLE_DESC           304
#define IDS_RIBBON_STATUSBAR            305
#define IDS_RIBBON_VIEW                 306
#define IDS_BUILD_TAB                   307
#define IDS_DEBUG_TAB                   308
#define IDS_FIND_TAB                    309
#define IDS_EDIT_MENU                   310
#define ID_DEFRAG_ANALYZE               311
#define ID_DEFRAG_FREE_SPACE            312
#define ID_DEFRAG_SIMPLE                313
#define ID_DEFRAG_PAUSE                 314
#define ID_DEFRAG_STOP                  315
#define IDS_RIBBON_SETTINGS             316
#define ID_DEFRAG_SETTINGS              317
#define ID_RIBBON_DEFRAG_PROGRESS       318
#define ID_SCHEDULER_NEW_ONETIME        319
#define ID_SCHEDULER_NEW_DAILY          320
#define ID_SCHEDULER_NEW_WEEKLY         321
#define ID_SCHEDULER_NEW_SCREENSAVER    322
#define ID_SCHEDULER_RUN                323
#define ID_VIEW_STYLE_BLOCKSIZECB       324
#define ID_VIEW_STYLE_SHOWLEGEND        325
#define ID_VIEW_STYLE_SETDEFAULT        326
#define ID_SCHEDULER_ENABLE             327
#define ID_SCHEDULER_EDIT               328
#define ID_SCHEDULER_DELETE             329
#define IDS_SCHEDULERVIEW_MENU          330
#define IDS_SCHEDULER_COL_STATUS        331
#define IDS_SCHEDULER_COL_ACTION        332
#define IDS_SCHEDULER_COL_TYPE          333
#define IDS_SCHEDULER_COL_LASTRUN       334
#define IDS_SCHEDULER_COL_RUNSTATUS     335
#define IDS_SCHEDULER_COL_NEXTRUN       336
#define ID_APP_OPEN                     337
#define ID_DEFRAG_COMPUTER              338
#define ID_DEFRAG_ORDER                 339
#define ID_DEFRAG_BY_NAME               340
#define ID_DEFRAG_BY_ACCESS             341
#define ID_DEFRAG_BY_MODIFY             342
#define ID_DEFRAG_BY_CREATION           343
#define ID_DEFRAG_BY_SIZE               344
#define ID_DEFRAG_BY_FORCE_FILL         345
#define IDS_RIBBON_REPORTS              346
#define IDS_RIBBON_REPORTS_CONTEXT      347
#define IDS_RIBBON_REPORTS_PANEL        348
#define IDS_RIBBON_REPORT_SAVE          349
#define IDS_RIBBON_REPORT_PRINT         350
#define IDS_RIBBON_REPORT_PRINT_SETUP   351
#define IDS_RIBBON_REPORT_PRINT_PREVIEW 352
#define ID_REPORT_PRINT_SETUP           353
#define ID_REPORT_PRINT_PREVIEW         354
#define ID_APP_UPDATE                   355
#define IDS_RIBBON_BUY                  356
#define ID_APP_BUY                      357
#define IDS_DRIVELIST_COL_NAME          360
#define IDS_DRIVELIST_COL_TYPE          361
#define IDS_DRIVELIST_COL_LABEL         362
#define IDS_DRIVELIST_COL_FILESYS       363
#define IDS_DRIVELIST_COL_SIZE          364
#define IDS_DRIVELIST_COL_FREE          365
#define IDS_DRIVELIST_COL_STATUS        366
#define IDS_DRIVELIST_COL_LAST          367
#define IDS_DRIVELIST_COL_FRAGMENTED    368
#define IDS_SERVICE_CONNECTION_ERROR    369
#define IDS_DRIVE_REMOVABLE             370
#define IDS_DRIVE_FIXED                 371
#define IDS_DRIVE_REMOTE                372
#define IDS_DRIVE_NO_ROOT_DIR           373
#define IDS_DRIVE_CDROM                 374
#define IDS_DRIVE_RAMDISK               375
#define IDS_STATE_READY                 376
#define IDS_NOT_ANALYSED_YET            377
#define IDS_DEFRAG_CMD_INIT_JOB         380
#define IDS_DEFRAG_CMD_ANALIZE_VOLUME   381
#define IDS_DEFRAG_CMD_DEBUG1           382
#define IDS_DEFRAG_CMD_SIMPLE_DEFRAG    383
#define IDS_DEFRAG_CMD_FREE_SPACE       384
#define IDS_DEFRAG_CMD_SMART_BY_NAME    385
#define IDS_DEFRAG_CMD_SMART_BY_ACCESS  386
#define IDS_DEFRAG_CMD_SMART_BY_MODIFY  387
#define IDS_DEFRAG_CMD_SMART_BY_SIZE    388
#define IDS_DEFRAG_CMD_SMART_BY_CREATE  389
#define IDS_DEFRAG_CMD_FORCE_TOGETHER   390
#define IDS_RIBBON_HELP                 391
#define IDS_RIBBON_HELP_PANEL           392
#define IDS_RIBBON_HELP_ACTION          393
#define IDB_HELPSMALL                   394
#define IDB_HELPLARGE                   395
#define IDS_RIBBON_LICENSE_PANEL        396
#define IDS_LICENSE_INFO                397
#define IDS_RIBBON_UPDATE_PANEL         398
#define IDS_VERSION_INFO                399
#define IDS_RIBBON_UPDATE               400
#define IDS_OVERAL_FRAGMENTATION        401
#define IDS_OVERAL_RECOMEND_GOOD        402
#define IDS_OVERAL_RECOMEND_POOR        403
#define IDS_OVERAL_RECOMEND_BAD         404
#define IDS_MFT_FRAGMENTATION           405
#define IDS_MFT_RECOMEND_GOOD           406
#define IDS_MFT_RECOMEND_POOR           407
#define IDS_MFT_RECOMEND_BAD            408
#define IDS_PAGEFILE_FRAGMENTATION      409
#define IDS_PAGEFILE_RECOMEND_GOOD      410
#define IDS_PAGEFILE_RECOMEND_POOR      411
#define IDS_PAGEFILE_RECOMEND_BAD       412
#define IDS_FREESPACE_FRAGMENTATION     413
#define IDS_FREESPACE_RECOMEND_GOOD     414
#define IDS_FREESPACE_RECOMEND_POOR     415
#define IDS_FREESPACE_RECOMEND_BAD      416
#define IDS_HEALTH_EXCELLENT            420
#define IDS_HEALTH_EXCELLENT_DESC       421
#define IDS_HEALTH_GOOD                 422
#define IDS_HEALTH_GOOD_DESC            423
#define IDS_HEALTH_PASSED               424
#define IDS_HEALTH_PASSED_DESC          425
#define IDS_HEALTH_POOR                 426
#define IDS_HEALTH_POOR_DESC            427
#define IDS_HEALTH_DRAMATIC             428
#define IDS_HEALTH_DRAMATIC_DESC        429
#define IDS_REPORT_DRIVE_INFO           430
#define IDS_REPORT_FRAGMENTATION        431
#define IDS_REPORT_DRIVE_HEALTH         432
#define IDS_REPORT_FILE_ORGANIZATION    433
#define IDS_REPORT_100_FRAGMENTED       434
#define IDS_REPORT_EXCLUDED             435
#define IDS_TASKPANE_MAIN_TASKS         440
#define IDS_TASKPANE_MAIN_DETAILS       441
#define IDS_TASKPANE_DETAILS_INFO       442
#define IDS_TASKPANE_RESULT             443
#define IDS_TASKPANE_RESULT_NOTE        444
#define IDS_TASKPANE_RESULT_MAIN        445
#define IDS_TASKPANE_RESULT_RECOMEND    446
#define IDS_TASKPANE_RESULT_RELIABILITY 447
#define IDS_TASKPANE_RESULT_MFT         448
#define IDS_TASKPANE_RESULT_PAGEFILE    449
#define IDS_TASKPANE_RESULT_FREE        450
#define IDS_RIBBON_DEFRAG_RECOMMEND     451
#define ID_DEFRAG_RECOMMEND             452
#define IDC_URL_PRODUCT                 1001
#define IDC_URL_PRODUCT2                1002
#define IDC_URL_SUPPORT                 1002
#define IDC_LICENSE_INFO                1003
#define ID_CANCEL_EDIT_CNTR             32768
#define ID_WRITE_PASTEASHYPERLINK       32770
#define ID_ACCELERATOR32774             32774
#define ID_DEFRAGVIEWPOPUP_RECOMMEND    32776
#define ID_DEFRAG_MOSTRECOMMENDED       32777

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        460
#define _APS_NEXT_COMMAND_VALUE         32778
#define _APS_NEXT_CONTROL_VALUE         1004
#define _APS_NEXT_SYMED_VALUE           460
#endif
#endif
